### ISSUE TITLE
Android Studio - installing problem

### ISSUE THREAD

**Issue by PepaZapletal** [threema-ch/webrtc-android#4]
Hi,

I added this line:

`compile 'ch.threema:webrtc-android:91.0.1'`

to my build.gradle file and it's not working. I get this message:

`No cached version of ch.threema:webrtc-android:91.0.1 available for offline mode.'` - but I'm online and everythings is OK

I also added to my project build.gradle file `mavenCentral()`

What is wrong? What should I do?

Thanks for help.

**Comment by threema-danilo** [comment]
It seems that you enabled offline mode in Android Studio: https://stackoverflow.com/questions/24144598/no-cached-version-of-gradle

Keep in mind that this version of WebRTC contains about a dozen custom patches specific to Threema. We offer no support for this package outside of Threema.
